ParseGen::Parser::Yacc::LexYaccGenerator
Util::ParseableInput* ParseGen::Parser::Yacc::LexYaccGenerator::rules
Referenced by LexYaccGenerator, codeToString.
ParseGen::Parser::Yacc::LexYaccGenerator::LexYaccGenerator(std::string language, std::string bnf)
References ParseGen::Parser::IParserGenerator::bnf, ParseGen::Parser::IParserGenerator::language, rules, ParseGen::Parser::IParserGenerator::templateSubDir.
Referenced by Create.
std::string ParseGen::Parser::Yacc::LexYaccGenerator::escaped_name(std::string name)
References GET_UCN.
Referenced by codeToString.
Util::ParseTree* ParseGen::Parser::Yacc::LexYaccGenerator::parse(std::string input)
References ParseGen::Parser::Util::END.
std::string ParseGen::Parser::Yacc::LexYaccGenerator::codeToString()
References escaped_name, ParseGen::Parser::Util::Symbol::name, ParseGen::Parser::Util::ParseableInput::productions, rules, ParseGen::Parser::Util::ParseableInput::start.
static IParserGenerator* ParseGen::Parser::Yacc::LexYaccGenerator::Create(std::string language, std::string bnf)
References ParseGen::Parser::IParserGenerator::bnf, ParseGen::Parser::IParserGenerator::language, LexYaccGenerator.
Referenced by ParseGen::Parser::ParserGeneratorFactory::ParserGeneratorFactory.