ParseGen::GUI::ParseTree::Renderer
Parser::Util::ParseTree* ParseGen::GUI::ParseTree::Renderer::parseTree
Referenced by buchheim, simpleDraw, render.
std::vector<TreeRect> ParseGen::GUI::ParseTree::Renderer::nodes
Referenced by createGeometry, render.
std::vector<TreeEdge> ParseGen::GUI::ParseTree::Renderer::edges
Referenced by createGeometry, render.
Renderer * ParseGen::GUI::ParseTree::Renderer::Get()
Referenced by ParseGen::GUI::MainEditor::drawTree.
void ParseGen::GUI::ParseTree::Renderer::render(Parser::Util::ParseTree *parseTree)
References buchheim, createGeometry, edges, nodes, parseTree.
TreeRect ParseGen::GUI::ParseTree::Renderer::createGeometry(Parser::Util::Node *parseTree)
References edges, ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Symbol::isTerminal, ParseGen::GUI::ParseTree::TreeRect::max, ParseGen::GUI::ParseTree::TreeRect::min, ParseGen::Parser::Util::Symbol::name, nodes, ParseGen::Parser::Util::Node::value, ParseGen::Parser::Util::Node::x, ParseGen::Parser::Util::Node::y.
Referenced by render.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::buchheim(Parser::Util::Node *parseTree)
References firstWalk, parseTree, secondWalk, thirdWalk.
Referenced by render.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::firstWalk(Parser::Util::Node *v, float distance)
References apportion, executeShifts, ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Node::isLeaf, ParseGen::Parser::Util::Node::leftBrother, ParseGen::Parser::Util::Node::leftmostSibling, ParseGen::Parser::Util::Node::mod, ParseGen::Parser::Util::Node::x.
Referenced by buchheim.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::apportion(Parser::Util::Node *v, Parser::Util::Node *defaultAncestor, float distance)
References ancestor, ParseGen::Parser::Util::Node::leftBrother, ParseGen::Parser::Util::Node::leftmostSibling, ParseGen::Parser::Util::Node::mod, moveSubtree.
Referenced by firstWalk.
void ParseGen::GUI::ParseTree::Renderer::executeShifts(Parser::Util::Node *v)
References ParseGen::Parser::Util::Node::getChildren.
Referenced by firstWalk.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::ancestor(Parser::Util::Node *vil, Parser::Util::Node *v, Parser::Util::Node *defaultAncestor)
References ParseGen::Parser::Util::Node::ancestor, ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Node::parent.
Referenced by apportion.
float ParseGen::GUI::ParseTree::Renderer::secondWalk(Parser::Util::Node *v, float m, float depth, float min)
References ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Node::mod, PG_FLOAT_INF, ParseGen::Parser::Util::Node::x, ParseGen::Parser::Util::Node::y.
Referenced by buchheim.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::thirdWalk(Parser::Util::Node *tree, float n)
References ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Node::x.
Referenced by buchheim.
void ParseGen::GUI::ParseTree::Renderer::moveSubtree(Parser::Util::Node *wl, Parser::Util::Node *wr, float shift)
References ParseGen::Parser::Util::Node::change, ParseGen::Parser::Util::Node::mod, ParseGen::Parser::Util::Node::number, ParseGen::Parser::Util::Node::shift, ParseGen::Parser::Util::Node::x.
Referenced by apportion.
Parser::Util::Node * ParseGen::GUI::ParseTree::Renderer::simpleDraw(Parser::Util::Node *parseTree)
References ParseGen::Parser::Util::Node::getChildren, parseTree.