ParseGen::Parser::Util::Node
float ParseGen::Parser::Util::Node::x
Referenced by ParseGen::GUI::ParseTree::Renderer::firstWalk, ParseGen::GUI::ParseTree::Renderer::moveSubtree, ParseGen::GUI::ParseTree::Renderer::secondWalk, ParseGen::GUI::ParseTree::Renderer::thirdWalk, ParseGen::GUI::ParseTree::Renderer::createGeometry.
float ParseGen::Parser::Util::Node::y
Referenced by Node, ParseGen::GUI::ParseTree::Renderer::secondWalk, ParseGen::GUI::ParseTree::Renderer::createGeometry.
float ParseGen::Parser::Util::Node::mod
Referenced by ParseGen::GUI::ParseTree::Renderer::firstWalk, ParseGen::GUI::ParseTree::Renderer::apportion, ParseGen::GUI::ParseTree::Renderer::moveSubtree, ParseGen::GUI::ParseTree::Renderer::secondWalk.
float ParseGen::Parser::Util::Node::shift
Referenced by ParseGen::GUI::ParseTree::Renderer::moveSubtree.
float ParseGen::Parser::Util::Node::change
Referenced by ParseGen::GUI::ParseTree::Renderer::moveSubtree.
Node* ParseGen::Parser::Util::Node::thread
Referenced by left, right.
Node* ParseGen::Parser::Util::Node::ancestor
Referenced by Node, ParseGen::GUI::ParseTree::Renderer::ancestor.
Node* ParseGen::Parser::Util::Node::parent
Referenced by leftBrother, leftmostSibling, number, ParseGen::GUI::ParseTree::Renderer::ancestor.
Symbol ParseGen::Parser::Util::Node::value
Referenced by print, json, ParseGen::Parser::Util::ParseTree::isStub, ParseGen::Parser::Util::ParseTree::print, ParseGen::GUI::ParseTree::Renderer::createGeometry.
std::vector<Node *> ParseGen::Parser::Util::Node::children
Referenced by addChildren, print, json, getChildren, isLeaf, left, right.
ParseGen::Parser::Util::Node::Node(Symbol val)
References ancestor, y.
Referenced by addChildren.
ParseGen::Parser::Util::Node::Node(Symbol val, Node *parent)
References ancestor, y.
void ParseGen::Parser::Util::Node::addChildren(std::initializer_list< Symbol > children)
References children, Node.
Referenced by ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse.
void ParseGen::Parser::Util::Node::addChildren(std::vector< Symbol > children)
References children, Node.
void ParseGen::Parser::Util::Node::print(std::string prefix="")
References children, ParseGen::Parser::Util::Symbol::name, value.
std::string ParseGen::Parser::Util::Node::json()
References children, ParseGen::Parser::Util::EMPTY, ParseGen::Parser::Util::END, ParseGen::Parser::Util::Symbol::getType, ParseGen::Parser::Util::Symbol::name, ParseGen::Parser::Util::NON_TERMINAL, ParseGen::Parser::Util::TERMINAL, value.
std::vector<Node *> ParseGen::Parser::Util::Node::getChildren()
References children.
Referenced by ParseGen::GUI::ParseTree::Renderer::ancestor, ParseGen::GUI::ParseTree::Renderer::createGeometry, ParseGen::GUI::ParseTree::Renderer::executeShifts, ParseGen::GUI::ParseTree::Renderer::firstWalk, leftBrother, leftmostSibling, number, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse, ParseGen::GUI::ParseTree::Renderer::secondWalk, ParseGen::GUI::ParseTree::Renderer::simpleDraw, ParseGen::GUI::ParseTree::Renderer::thirdWalk.
bool ParseGen::Parser::Util::Node::isLeaf()
References children.
Referenced by ParseGen::GUI::ParseTree::Renderer::firstWalk.
Node* ParseGen::Parser::Util::Node::leftBrother()
References getChildren, parent.
Referenced by ParseGen::GUI::ParseTree::Renderer::apportion, ParseGen::GUI::ParseTree::Renderer::firstWalk.
Node* ParseGen::Parser::Util::Node::leftmostSibling()
References getChildren, parent.
Referenced by ParseGen::GUI::ParseTree::Renderer::apportion, ParseGen::GUI::ParseTree::Renderer::firstWalk.
int ParseGen::Parser::Util::Node::number()
References getChildren, parent.
Referenced by ParseGen::GUI::ParseTree::Renderer::moveSubtree.
Node* ParseGen::Parser::Util::Node::left()
References children, thread.
Node* ParseGen::Parser::Util::Node::right()
References children, thread.
std::ostream& operator<<(std::ostream &stream, const Node &w)