ParseGen::GUI::MainEditor
const char* ParseGen::GUI::MainEditor::m_WindowTitle
Referenced by Start.
int ParseGen::GUI::MainEditor::m_WindowWidth
Referenced by framebuffer_size_callback, Start, RenderFrame.
int ParseGen::GUI::MainEditor::m_WindowHeight
Referenced by framebuffer_size_callback, Start, RenderFrame.
std::vector<Rule> ParseGen::GUI::MainEditor::m_Rules
Referenced by deleteRule, addRule, rulesCollapseGui, RenderFrame, processRules.
std::vector<std::string> ParseGen::GUI::MainEditor::inputs
Referenced by ruleTesterWindow.
Parser::IParserGenerator* ParseGen::GUI::MainEditor::parser
Referenced by ruleTesterWindow, processRules.
ParseGen::GUI::MainEditor::MainEditor(const char *windowTitle, int windowWidth, int windowHeight)
ParseGen::GUI::MainEditor::~MainEditor()
References ParseGen::GUI::NonTerminal::allNonTerminals.
void ParseGen::GUI::MainEditor::Start()
References initGLFW, m_WindowHeight, m_WindowTitle, m_WindowWidth, RenderFrame, teardown.
Referenced by main.
void ParseGen::GUI::MainEditor::RenderFrame(float deltaTime)
References addRule, m_Rules, m_WindowHeight, m_WindowWidth, nonTerminalsCollapseGui, rulesCollapseGui, ruleTesterWindow.
Referenced by Start.
void ParseGen::GUI::MainEditor::addRule(std::string name)
References ParseGen::GUI::NonTerminal::allNonTerminals, m_Rules.
Referenced by RenderFrame, rulesCollapseGui.
GLFWwindow * ParseGen::GUI::MainEditor::initGLFW(std::string programName, int width, int height)
References teardown.
Referenced by Start.
void ParseGen::GUI::MainEditor::framebuffer_size_callback(GLFWwindow *window, int width, int height)
References m_WindowHeight, m_WindowWidth.
void ParseGen::GUI::MainEditor::teardown(GLFWwindow *window)
Referenced by initGLFW, Start.
void ParseGen::GUI::MainEditor::deleteRule(int index)
References m_Rules.
Referenced by rulesCollapseGui.
int ParseGen::GUI::MainEditor::rulesCollapseGui()
References addRule, deleteRule, m_Rules.
Referenced by RenderFrame.
void ParseGen::GUI::MainEditor::nonTerminalsCollapseGui()
References ParseGen::GUI::NonTerminal::allNonTerminals.
Referenced by RenderFrame.
void ParseGen::GUI::MainEditor::drawTree(Parser::Util::ParseTree *parseTree)
References ParseGen::GUI::ParseTree::Renderer::Get.
Referenced by ruleTesterWindow.
void ParseGen::GUI::MainEditor::ruleTesterWindow(bool *open)
References ParseGen::Parser::IParserGenerator::bnf, ParseGen::Parser::IParserGenerator::codeToFile, drawTree, ParseGen::Parser::ParserGeneratorFactory::Get, ParseGen::Parser::ParserGeneratorFactory::getOutputTypes, inputs, ParseGen::Parser::Util::ParseTree::isStub, ParseGen::Parser::IParserGenerator::parse, parser, processRules.
Referenced by RenderFrame.
Parser::IParserGenerator * ParseGen::GUI::MainEditor::processRules(std::string, std::string)
References ParseGen::Parser::ParserGeneratorFactory::Create, m_Rules, parser.
Referenced by ruleTesterWindow.