ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator
bool ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::firstParse
Referenced by parse, codeToString.
Util::ParseableInput* ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::rules
Referenced by LLPredictiveParserGenerator, parse, codeToString.
ParserTable* ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parseTable
Referenced by generateParseTable, parse.
std::string ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::output
ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::LLPredictiveParserGenerator(std::string language, std::string bnf)
References ParseGen::Parser::IParserGenerator::bnf, ParseGen::Parser::IParserGenerator::language, rules, ParseGen::Parser::IParserGenerator::templateSubDir.
Referenced by Create.
ParserTable* ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::generateParseTable(Util::ParseableInput input)
References ParseGen::Parser::Util::END, ParseGen::Parser::LLPredictiveParser::ParserTable::first, ParseGen::Parser::Util::ParseableInput::first, ParseGen::Parser::LLPredictiveParser::ParserTable::follow, ParseGen::Parser::Util::ParseableInput::follow, ParseGen::Parser::LLPredictiveParser::ParserTable::insert, ParseGen::Parser::LLPredictiveParser::ParserTable::isError, parseTable, ParseGen::Parser::Util::ParseableInput::productions, ParseGen::Parser::Util::ParseableInput::start.
Referenced by codeToString, parse.
Util::ParseTree* ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse(std::string input)
References ParseGen::Parser::Util::Node::addChildren, ParseGen::Parser::Util::END, ParseGen::Parser::LLPredictiveParser::ParserTable::first, firstParse, generateParseTable, ParseGen::Parser::LLPredictiveParser::ParserTable::get, ParseGen::Parser::Util::Node::getChildren, ParseGen::Parser::Util::Symbol::isEmpty, ParseGen::Parser::Util::Symbol::isEnd, ParseGen::Parser::LLPredictiveParser::ParserTable::isError, ParseGen::Parser::LLPredictiveParser::ParserTable::isSynch, ParseGen::Parser::Util::Symbol::isTerminal, ParseGen::Parser::LLPredictiveParser::Token::lexeme, ParseGen::Parser::Util::Symbol::name, ParseGen::Parser::LLPredictiveParser::Lexer::next, ParseGen::Parser::Util::NON_TERMINAL, parseTable, ParseGen::Parser::LLPredictiveParser::Token::posStr, rules, ParseGen::Parser::LLPredictiveParser::ParserTable::start, ParseGen::Parser::Util::TERMINAL.
std::string ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::codeToString()
References ParseGen::Parser::LLPredictiveParser::ParserTable::creationCode, firstParse, generateParseTable, rules.
static IParserGenerator* ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::Create(std::string language, std::string bnf)
References ParseGen::Parser::IParserGenerator::bnf, ParseGen::Parser::IParserGenerator::language, LLPredictiveParserGenerator.
Referenced by ParseGen::Parser::ParserGeneratorFactory::ParserGeneratorFactory.