ParseGen::Parser::Util::Symbol
std::string ParseGen::Parser::Util::Symbol::name
Referenced by ParseGen::Parser::Yacc::LexYaccGenerator::codeToString, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse, ParseGen::Parser::LLPredictiveParser::ParserTable::creationCode, ParseGen::Parser::Util::ParseableInput::calcFirst, ParseGen::Parser::Util::Node::print, ParseGen::Parser::Util::Node::json, ParseGen::Parser::Util::ParseTree::print, ParseGen::Parser::Util::operator<, ParseGen::GUI::ParseTree::Renderer::createGeometry.
SymbolType ParseGen::Parser::Util::Symbol::type
Referenced by ParseGen::Parser::Util::operator<, isEmpty, isNonTerminal, isTerminal, isEnd, getType.
ParseGen::Parser::Util::Symbol::Symbol(std::string name, SymbolType type)
bool ParseGen::Parser::Util::Symbol::isEmpty() const
References ParseGen::Parser::Util::EMPTY, type.
Referenced by ParseGen::Parser::Util::ParseableInput::calcFirst, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse.
bool ParseGen::Parser::Util::Symbol::isNonTerminal() const
References ParseGen::Parser::Util::NON_TERMINAL, type.
Referenced by ParseGen::Parser::Util::ParseableInput::calcFirst.
bool ParseGen::Parser::Util::Symbol::isTerminal() const
References ParseGen::Parser::Util::EMPTY, ParseGen::Parser::Util::TERMINAL, type.
Referenced by ParseGen::Parser::Util::ParseableInput::calcFirst, ParseGen::GUI::ParseTree::Renderer::createGeometry, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse.
bool ParseGen::Parser::Util::Symbol::isEnd() const
References ParseGen::Parser::Util::END, type.
Referenced by ParseGen::Parser::Util::ParseTree::isStub, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::parse.
SymbolType ParseGen::Parser::Util::Symbol::getType() const
References type.
Referenced by ParseGen::Parser::LLPredictiveParser::ParserTable::creationCode, ParseGen::Parser::Util::Node::json.
bool operator<(const Symbol &, const Symbol &)
bool operator==(const Symbol &, const Symbol &)
bool operator!=(const Symbol &, const Symbol &)