ParseGen::Parser::ParserGeneratorFactory
std::map<std::string, IParserGenerator *(*)(std::string, std::string)> ParseGen::Parser::ParserGeneratorFactory::m_FactoryMap
Referenced by Register, create, size.
const char** ParseGen::Parser::ParserGeneratorFactory::options
Referenced by Register, getOutputTypes.
ParseGen::Parser::ParserGeneratorFactory::ParserGeneratorFactory()
References ParseGen::Parser::BNF::BNFParserGenerator::Create, ParseGen::Parser::Yacc::LexYaccGenerator::Create, ParseGen::Parser::LLPredictiveParser::LLPredictiveParserGenerator::Create, Register.
ParseGen::Parser::ParserGeneratorFactory::ParserGeneratorFactory(const ParserGeneratorFactory &)
ParserGeneratorFactory& ParseGen::Parser::ParserGeneratorFactory::operator=(const ParserGeneratorFactory &)
static ParserGeneratorFactory* ParseGen::Parser::ParserGeneratorFactory::Get()
Referenced by Create, GetOutputTypes, ParseGen::GUI::MainEditor::ruleTesterWindow, Size.
static IParserGenerator* ParseGen::Parser::ParserGeneratorFactory::Create(const std::string &type, const std::string &lang, const std::string &bnf)
References Get.
Referenced by ParseGen::GUI::MainEditor::processRules.
static const char** ParseGen::Parser::ParserGeneratorFactory::GetOutputTypes()
References Get.
static int ParseGen::Parser::ParserGeneratorFactory::Size()
References Get.
void ParseGen::Parser::ParserGeneratorFactory::Register(const std::string &type, IParserGenerator *(*pfnCreate)(std::string, std::string))
References m_FactoryMap, options.
Referenced by ParserGeneratorFactory.
IParserGenerator* ParseGen::Parser::ParserGeneratorFactory::create(const std::string &type, const std::string &lang, const std::string &bnf)
References m_FactoryMap.
const char** ParseGen::Parser::ParserGeneratorFactory::getOutputTypes() const
References options.
Referenced by ParseGen::GUI::MainEditor::ruleTesterWindow.
int ParseGen::Parser::ParserGeneratorFactory::size() const
References m_FactoryMap.